# Change these first
owner: trivision-hans
repo: uptime

sites:
  - name: pi
    url: https://pi.trivision.io
  - name: auth
    url: https://auth.pi.trivision.io/
  - name: (health) api
    url: https://api.pi.trivision.io/healthz
  - name: (health) pi
    url: https://pi.trivision.io/api/health
  - name: trivision.io
    url: https://trivision.io/wp-json

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: uptime
  logoUrl: https://raw.githubusercontent.com/trivision-hans/uptime/master/assets/trivision_icon.svg
  faviconSvg: https://raw.githubusercontent.com/trivision-hans/uptime/master/assets/trivision_icon3.svg
  name: Trivision uptime
  introTitle: "Uptime monitoring."
  introMessage: "This page provides real-time monitoring for our critical services, powered by [Upptime](https://upptime.js.org), an open-source uptime tracker built on GitHub. "
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
